import Navbar from '@/components/Navbar'
import './globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}
                <Navbar />
                <Toaster />
            </body>
        </html>
    )
}